### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by trulyronak** [flowforfrank/breakout#1]
Hi!

I found your [tutorial](https://www.webtips.dev/building-the-game-breakout-using-javascript), and really enjoyed it - i was wondering if you could add a license (I wanted to build off of this to make a multiplayer game) to see if I can use the code.

**Comment by flowforfrank** [comment]
Hi @trulyronak, thank you for your comment. I added a license for you:
https://github.com/flowforfrank/breakout/blob/master/LICENSE
